#!/bin/bash
# Script de Comandos Rápidos - AI Model Discovery
# Ejecuta este script para ver todos los comandos disponibles

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║     🤖 AI Model Discovery - Comandos Rápidos                    ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""

echo "📦 INSTALACIÓN"
echo "──────────────────────────────────────────────────────────────────"
echo "  sudo apt install python3-pip"
echo "  pip3 install -r requirements.txt"
echo ""

echo "🧪 PRUEBAS"
echo "──────────────────────────────────────────────────────────────────"
echo "  python3 test_search_engine.py              # Test automatizado"
echo ""

echo "🌐 INTERFAZ WEB"
echo "──────────────────────────────────────────────────────────────────"
echo "  python3 run_app.py                         # Iniciar app"
echo "  streamlit run app/main.py                  # Iniciar directo"
echo "  streamlit run app/main.py --server.port 8080  # Puerto custom"
echo ""

echo "💻 CLI"
echo "──────────────────────────────────────────────────────────────────"
echo "  # Búsqueda básica"
echo "  python3 -m search.non_federated.cli search \"PyTorch models\""
echo ""
echo "  # Búsqueda detallada"
echo "  python3 -m search.non_federated.cli search \"high rated models\" --verbose --show-sparql"
echo ""
echo "  # Estadísticas"
echo "  python3 -m search.non_federated.cli stats"
echo ""
echo "  # Generar SPARQL"
echo "  python3 -m search.non_federated.cli sparql \"NLP models\""
echo ""

echo "🐍 PYTHON API"
echo "──────────────────────────────────────────────────────────────────"
echo "  python3 -c \""
echo "from search.non_federated import create_api"
echo "from notebooks import create_test_graph"
echo "api = create_api(graph=create_test_graph())"
echo "results = api.search('PyTorch models')"
echo "print(f\\\"Found: {results['total_results']} models\\\")"
echo "\""
echo ""

echo "📊 NOTEBOOKS"
echo "──────────────────────────────────────────────────────────────────"
echo "  jupyter notebook notebooks/03_text_to_sparql_validation.ipynb"
echo ""

echo "📚 DOCUMENTACIÓN"
echo "──────────────────────────────────────────────────────────────────"
echo "  cat SUMMARY.md                             # Resumen completo"
echo "  cat README_NEXT_STEPS.md                   # Próximos pasos"
echo "  cat QUICKSTART_WEB.md                      # Guía rápida web"
echo "  cat IMPLEMENTATION_SUMMARY.md              # Detalles técnicos"
echo ""

echo "🔍 EJEMPLOS DE BÚSQUEDA"
echo "──────────────────────────────────────────────────────────────────"
echo "  # Búsquedas básicas"
echo "  python3 -m search.non_federated.cli search \"list all AI models\""
echo "  python3 -m search.non_federated.cli search \"PyTorch models\""
echo "  python3 -m search.non_federated.cli search \"models from HuggingFace\""
echo ""
echo "  # Búsquedas con filtros"
echo "  python3 -m search.non_federated.cli search \"high rated NLP models\""
echo "  python3 -m search.non_federated.cli search \"computer vision models\""
echo "  python3 -m search.non_federated.cli search \"models with rating above 4.7\""
echo ""
echo "  # Búsquedas con agregación"
echo "  python3 -m search.non_federated.cli search \"count models by task\""
echo "  python3 -m search.non_federated.cli search \"average rating per repository\""
echo ""

echo "🎯 DEMO RÁPIDO (3 COMANDOS)"
echo "──────────────────────────────────────────────────────────────────"
echo "  python3 test_search_engine.py              # 1. Verificar sistema"
echo "  python3 -m search.non_federated.cli stats  # 2. Ver estadísticas"
echo "  python3 run_app.py                         # 3. Abrir interfaz web"
echo ""

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║  💡 TIP: Ejecuta 'python3 run_app.py' para la mejor experiencia ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
